supervisor <- read.table(file="C:/Users/lynsi/Desktop/Stat 330/Supervisor.txt", header=TRUE)
supervisor <- data.frame(supervisor)
pairs(supervisor, main="Scores (from 0 to 100) on Survey Variables")
cor(supervisor)
matrix <- cor(supervisor)
mean(matrix[,1:4])
mean(matrix[,5:6])
library(car)
modelr<-lm(Rating~.,data=supervisor)
